-- CREATE TABLES 

CREATE TABLE CLUB (
    CLUB_ID NUMBER PRIMARY KEY, 
    CLUB_NAME VARCHAR(20) NOT NULL, 
    STREET_ADDRES VARCHAR(40) NOT NULL, 
    CITY VARCHAR(30) NOT NULL, 
    STATE CHAR(2) NOT NULL,
    ZIPCODE VARCHAR(10) NOT NULL, 
    PHONE VARCHAR(15) NOT NULL
); 

CREATE TABLE MEMBER (
    MEMBER_ID CHAR(5) PRIMARY KEY, 
    FIRST_NAME VARCHAR(10) NOT NULL, 
    LAST_NAME VARCHAR(10) NOT NULL, 
    STREET_ADDRESS VARCHAR(40) NOT NULL, 
    CITY VARCHAR(30) NOT NULL, 
    STATE CHAR(2) NOT NULL, 
    ZIPCODE VARCHAR(10) NOT NULL
); 

CREATE TABLE MEMBERSHIP(
    MEMBERSHIP_ID VARCHAR(5) PRIMARY KEY, 
    MEMBER_ID CHAR(5) NOT NULL, 
    CLUB_ID NUMBER NOT NULL, 
    JOIN_DATE DATE NOT NULL, 
    END_DATE  DATE , 
    REASON VARCHAR(20), 
    ENTIRE_LIFE_MEMBER VARCHAR(3),
    FOREIGN KEY (MEMBER_ID) REFERENCES MEMBER,
    FOREIGN KEY (CLUB_ID) REFERENCES CLUB

);


CREATE TABLE PHONE(
    PHONE_ID NUMBER PRIMARY KEY,
    MEMBER_ID CHAR (5) NOT NULL, 
    PHONE_TYPE VARCHAR(15) NOT NULL, 
    PHONE_NUMBER VARCHAR(10) NOT NULL, 
    FOREIGN KEY (MEMBER_ID) REFERENCES MEMBER
);

CREATE TABLE AWARD 
(
    AWARD_ID VARCHAR(5) PRIMARY KEY, 
    AWARD_NAME VARCHAR(30) NOT NULL, 
    DESCRIPTION VARCHAR (15)
);

CREATE TABLE TALENT
(
    TALENT_ID VARCHAR(5) PRIMARY KEY,
    TALENT_NAME VARCHAR(30) NOT NULL,
    DESCRIPTION VARCHAR (15)

);

CREATE TABLE MEMBER_TALENT
(
    MEMBER_ID CHAR (5) NOT NULL, 
    TALENT_ID VARCHAR(5) NOT NULL,
    PRIMARY KEY (MEMBER_ID, TALENT_ID), 
    FOREIGN KEY (MEMBER_ID) REFERENCES MEMBER (MEMBER_ID),
    FOREIGN KEY (TALENT_ID) REFERENCES TALENT (TALENT_ID) 
);


CREATE TABLE MEMBER_AWARD (
    MEMBER_AWARD_ID NUMBER PRIMARY KEY, 
    MEMBER_ID CHAR(5) NOT NULL,
    AWARD_ID VARCHAR (5) NOT NULL, 
    AWARD_DATE DATE NOT NULL,
    FOREIGN KEY (MEMBER_ID) REFERENCES MEMBER(MEMBER_ID), 
    FOREIGN KEY (AWARD_ID) REFERENCES AWARD(AWARD_ID)
);

CREATE TABLE OFFICE (
    OFFICE_ID CHAR(4) PRIMARY KEY, 
    CLUB_ID NUMBER NOT NULL, 
    OFFICE_NAME VARCHAR(20) NOT NULL, 
    DESCRIPTION VARCHAR (30)NOT NULL, 
    FOREIGN KEY (CLUB_ID) REFERENCES CLUB 
);


CREATE TABLE OFFICER (
    OFFICER_ID VARCHAR (5) PRIMARY KEY, 
    OFFICE_ID CHAR(4) NOT NULL,
    MEMBER_ID CHAR(5) NOT NULL,
    YEAR INTEGER,
    FOREIGN KEY (OFFICE_ID) REFERENCES OFFICE, 
    FOREIGN KEY (MEMBER_ID) REFERENCES MEMBER
);


CREATE TABLE PROJECT (
    PROJECT_ID VARCHAR(5) PRIMARY KEY, 
    CLUB_ID NUMBER NOT NULL, 
    PROJECT_NAME VARCHAR(15) NOT NULL, 
    DESCRIPTION VARCHAR(15) NOT NULL, 
    PROJECT_DATE DATE NOT NULL, 
    COST NUMBER(8,2), 
    REVENUE NUMBER(8,2),
    FOREIGN KEY (CLUB_ID) REFERENCES CLUB
 );

CREATE TABLE MEMBER_PROJECT (
    MEMBER_ID CHAR(5) NOT NULL, 
    PROJECT_ID VARCHAR(5) NOT NULL, 
    PRIMARY KEY (MEMBER_ID, PROJECT_ID), 
    FOREIGN KEY (MEMBER_ID) REFERENCES MEMBER (MEMBER_ID), 
    FOREIGN KEY (PROJECT_ID) REFERENCES PROJECT (PROJECT_ID) 
);
    



















