--- DROP TRIGGER & SEQUNCES

DROP TRIGGER INSERT_PHONE;
DROP TRIGGER INSERT_CLUB;
DROP TRIGGER INSERT_MEMBER_AWARD;
DROP SEQUENCE PHONE_SEQ;
DROP SEQUENCE CLUB_SEQ;
DROP SEQUENCE MEMBER_AWARD_SEQ;

----------------------------------------

-- DROP VIEWS

DROP VIEW LOCAL_CLUB_VIEW;
DROP VIEW ALL_MEMBER_VIEW;
DROP VIEW Fundraise_Pj_View;
DROP VIEW Award_View;
DROP VIEW Current_Member_View;
DROP VIEW Service_Project_View;
DROP VIEW Ser_Proj_Member;
DROP VIEW Curr_Local_Officer_View;
DROP VIEW Curr_National_Officer;
DROP VIEW All_Member_Project;
DROP VIEW National_History;
DROP VIEW ALL_MEMBER_LOCAL_OFFICE_VIEW;





